import { Link } from 'react-router-dom';

import CodeBlock from 'docs/server/ui/codeBlock/CodeBlock.tsx';
import HR from 'docs/server/ui/hr/HR.tsx';
import Page from 'docs/server/ui/page/Page.tsx';
import SimplePropertiesList from 'docs/server/ui/propertiesList/SimplePropertiesList.tsx';
import { H3, H4 } from 'docs/server/ui/typography/Typography.tsx';
import apiData from 'docs/server/apiData/apiData.ts';
import EmphasisCard from 'docs/server/ui/card/EmphasisCard.tsx';
import { adjustAutogeneratedProperties } from 'docs/server/ui/propertiesList/util.ts';

export default function Messages() {
  return (
    <Page
      pretitle="Rest API"
      pretitleLinkTo="/rest-apis"
      title="Messages"
      pageSubtitle="All available operations for listing and editing messages"
      showTableOfContents
    >
      <EmphasisCard>
        <p>
          <strong>Looking for the message data format?</strong>
        </p>
        <p>
          Check out the{' '}
          <Link to="/how-to/create-cord-messages">
            how-to guide for examples of the Cord message data format
          </Link>
        </p>
      </EmphasisCard>
      <section>
        <H3>List all messages in a thread</H3>
        <p>This endpoint returns information about all messages in a thread.</p>
        <H4>HTTP Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'http',
              languageDisplayName: 'HTTP',
              snippet: 'GET https://api.cord.com/v1/threads/<ID>/messages',
            },
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl "https://api.cord.com/v1/threads/<threadID>/messages" \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>'`,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord thread get-messages <THREAD_ID>`,
            },
          ]}
        />
        <br />
        <H4>Request Body</H4>
        <p>
          <em>This REST endpoint has no request body.</em>
        </p>
        <br />
        <H4 data-collapsible>Query Parameters</H4>
        <p>This endpoint can take the following options:</p>
        <SimplePropertiesList
          properties={
            apiData.types.ServerListThreadMessageParameters.properties
          }
          level={5}
        />
        <br />
        <H4 data-collapsible>Response</H4>
        <p>
          The response is a JSON Array of objects with the following fields:
        </p>
        <SimplePropertiesList
          level={5}
          showRequired={false}
          properties={apiData.types.CoreMessageData.properties}
        />
      </section>
      <HR />
      <section>
        <H3>List all messages</H3>
        <p>
          This endpoint returns information about all messages in the project.
          Most of the times, fetching messages for a specific thread should be
          preferred.
        </p>
        <H4>HTTP Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'http',
              languageDisplayName: 'HTTP',
              snippet: 'GET https://api.cord.com/v1/messages',
            },
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl "https://api.cord.com/v1/messages" \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>'`,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord message ls`,
            },
          ]}
        />
        <br />
        <H4>Request Body</H4>
        <p>
          <em>This REST endpoint has no request body.</em>
        </p>
        <br />
        <H4 data-collapsible>Query Parameters</H4>
        <p>This endpoint can take the following options:</p>
        <SimplePropertiesList
          properties={apiData.types.ServerListMessageParameters.properties}
          level={5}
        />
        <br />
        <H4 data-collapsible>Response</H4>
        <p>The response is an object with the following fields:</p>
        <SimplePropertiesList
          level={5}
          showRequired={false}
          properties={apiData.types.ServerListMessages.properties}
        />
      </section>
      <HR />
      <section>
        <H3>Get a message</H3>
        <p>This endpoint returns information about a single message.</p>
        <H4>HTTP Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'http',
              languageDisplayName: 'HTTP',
              snippet:
                'GET https://api.cord.com/v1/threads/<threadID>/messages/<messageID>',
            },
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl "https://api.cord.com/v1/threads/<threadID>/messages/<messageID>" \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>'`,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord message get <ID>`,
            },
          ]}
        />
        <H4>Request Body</H4>
        <p>
          <em>This REST endpoint has no request body.</em>
        </p>
        <H4 data-collapsible>Response</H4>
        <p>The response is an object with the following fields:</p>
        <SimplePropertiesList
          level={5}
          showRequired={false}
          properties={apiData.types.CoreMessageData.properties}
        />
      </section>
      <HR />
      <section>
        <H3>Create a message</H3>
        <p>This endpoint adds a new message to a thread.</p>
        <H4>HTTP Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'http',
              languageDisplayName: 'HTTP',
              snippet: 'POST https://api.cord.com/v1/threads/<ID>/messages',
            },
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl "https://api.cord.com/v1/threads/<threadID>/messages" \\
  -X POST \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>'\\
  -H 'Content-Type: application/json' `,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord message create [ID]`,
            },
          ]}
        />
        <H4 data-collapsible>Request Body</H4>
        <SimplePropertiesList
          level={5}
          properties={adjustAutogeneratedProperties(
            apiData.types.ServerCreateMessage.properties,
            { moveToBack: ['createThread'] },
          )}
        />
        <H4>Example Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl "https://api.cord.com/v1/threads/xyz456/messages" \\
  -X POST \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>' \\
  --json '{
    "id": "abc123",
    "authorID": "user123",
    "content": [{
      "type": "p",
      "children": [
        {
          "type": "mention",
          "user": { "id": "user456" },
          "children": [{"text": "@Zoidberg"}]
        },
        {
          "text": " Can you take a look at this?"
        }
      ]
    }]
  }'`,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord message create abc123 --thread-id=xyz456 --author-id=user123 
--content='[{
  "type": "p",
  "children": [
    {
      "type": "mention",
      "user": { "id": "user456" },
      "children": [{ "text": "@Fry" }]
    },
    {
      "text": "Can you take a look at this?"
    }
  ]}]'`,
            },
          ]}
        />
        <H4>Response</H4>
        <p>If successful, the response will be:</p>
        <CodeBlock
          snippetList={[
            {
              language: 'json',
              languageDisplayName: 'JSON',
              snippet: `{
  "success": true,
  "message": "Message created.",
  "messageID": "abc123"
}`,
            },
          ]}
        />
      </section>
      <HR />
      <section>
        <H3>Update a message</H3>
        <p>Use this endpoint to update an existing message.</p>
        <H4>HTTP Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'http',
              languageDisplayName: 'HTTP',
              snippet: `PUT https://api.cord.com/v1/threads/<threadID>/messages/<messageID>`,
            },
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl "https://api.cord.com/v1/threads/<threadID>/messages/<messageID>" \\
  -X PUT \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>'\\
  -H 'Content-Type: application/json' `,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord message update <ID>`,
            },
          ]}
        />
        <H4 data-collapsible>Request Body</H4>
        <p>
          Listed below are the fields of the request body to be added as part of
          the HTTP PUT request.
        </p>
        <SimplePropertiesList
          level={5}
          properties={adjustAutogeneratedProperties(
            apiData.types.ServerUpdateMessage.properties,
            { moveToBack: ['deleted', 'deletedTimestamp'] },
          )}
        />
        <HR />
        <H4>Response</H4>
        <p>If successful, the response will be:</p>
        <CodeBlock
          snippetList={[
            {
              language: 'json',
              languageDisplayName: 'JSON',
              snippet: `{
  "success": true,
  "message": "✅ You successfully updated message abc123"
}`,
            },
          ]}
        />
      </section>
      <HR />
      <section>
        <H3>Delete a message</H3>
        <p>This endpoint deletes a message.</p>
        <H4>HTTP Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'http',
              languageDisplayName: 'HTTP',
              snippet:
                'DELETE https://api.cord.com/v1/threads/<threadID>/messages/<messageID>',
            },
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl "https://api.cord.com/v1/threads/<threadID>/messages/<messageID>" \\
  -X DELETE \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>'`,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord message delete <ID>`,
            },
          ]}
        />
        <H4>Request Body</H4>
        <p>
          <em>This REST endpoint has no request body.</em>
        </p>
        <H4>Response</H4>
        <p>If successful, the response will be:</p>
        <CodeBlock
          snippetList={[
            {
              language: 'json',
              languageDisplayName: 'JSON',
              snippet: `{
  "success": true,
  "message": "💀 You successfully deleted message abc123"
}`,
            },
          ]}
        />
      </section>
    </Page>
  );
}
