export const SIDEBAR_CONTAINER_ID = '__CORD-SIDEBAR__';
export const LAUNCHER_CONTAINER_ID = '__CORD-LAUNCHER__';
export const SIDEBAR_OVERLAY_ID = '__CORD-SIDEBAR-OVERLAY__';
export const ACTION_MODAL_ID = '__CORD-ACTION-MODAL__';
export const ACTION_BOX_ID = '__CORD-ACTION-BOX__';
