// General sizing
const XSMALL = 2;
const SMALL = 4;
const MEDIUM = 8;
const LARGE = 16;
const XLARGE = 24;
const XXLARGE = 32;
const XXXLARGE = 48;

const AVATAR_BORDER_WIDTH_PX = XSMALL;

const CHECKBOX_DEFAULT_SIZE_PX = LARGE;
const MAIN_CHAT_AVATAR_SIZE_PX = XLARGE + AVATAR_BORDER_WIDTH_PX * 2;
const MAIN_CHAT_AVATAR_MARGIN_RIGHT_PX = MEDIUM;

export const Sizes = {
  // Sidebar
  SIDEBAR_COMPACT_WIDTH: 312, // used when viewport width is <= VIEWPORT_WIDTH_BREAKPOINT
  SIDEBAR_NORMAL_WIDTH: 416, // used when viewport width is > VIEWPORT_WIDTH_BREAKPOINT
  SIDEBAR_MAX_WIDTH: 500,
  VIEWPORT_WIDTH_BREAKPOINT: 1440,

  // Navigation top bar
  NAVIGATION_ITEM_SPACING_COMPACT: 12,
  NAVIGATION_ITEM_SPACING_NORMAL: LARGE,

  // subtract MEDIUM here, add it to the sidebar App.tsx container paddingBottom, to allow shadows to be visible
  SIDEBAR_BOTTOM_SPACE: 96 - MEDIUM,

  // Text
  X_SMALL_TEXT_SIZE_PX: 10,
  SMALL_TEXT_SIZE_PX: 12,
  DEFAULT_TEXT_SIZE_PX: 14,
  LARGE_TEXT_SIZE_PX: 18,
  X_LARGE_TEXT_SIZE_PX: 24,
  SMALL_LINE_HEIGHT_PX: 16,
  DEFAULT_LINE_HEIGHT_PX: 20,
  LARGE_LINE_HEIGHT_PX: 24,
  X_LARGE_LINE_HEIGHT_PX: 32,
  BOLD_TEXT_WEIGHT: 700,
  NORMAL_TEXT_WEIGHT: 400,

  // Spacing
  SMALL_PADDING_PX: 6,
  DEFAULT_PADDING_PX: 12,

  DEFAULT_BORDER_RADIUS: SMALL,
  LARGE_BORDER_RADIUS: MEDIUM,
  SMALL_BORDER_RADIUS: XSMALL,

  // Icon
  DEFAULT_ICON_PADDING_PX: 4,

  // Profile pics
  PAGE_VISITORS_AVATAR_SIZE_PX: XLARGE + AVATAR_BORDER_WIDTH_PX * 2,
  MAIN_CHAT_AVATAR_SIZE_PX,
  MAIN_CHAT_AVATAR_MARGIN_RIGHT_PX,
  MESSAGE_LEFT_PADDING:
    MAIN_CHAT_AVATAR_SIZE_PX + MAIN_CHAT_AVATAR_MARGIN_RIGHT_PX,
  AVATAR_BORDER_WIDTH_PX,
  FACEPILE_AVATAR_OVERLAP_SIZE_PX: SMALL,
  NOTIFICATION_FACEPILE_SIZE: LARGE + AVATAR_BORDER_WIDTH_PX * 2,

  // Composer
  COMPOSER_ADD_BUTTON_HEIGHT_PX: XXLARGE,
  COMPOSER_ADD_BUTTON_WIDTH_PX: XXLARGE,
  COMPOSER_HORIZONTAL_PADDING: MEDIUM,
  COMPOSER_VERTICAL_PADDING: 18,
  MAX_COMPOSER_EDITOR_HEIGHT: 448,

  // Messages
  MESSAGE_BLOCK_BOTTOM_MARGIN: XLARGE,
  MESSAGE_BOTTOM_MARGIN: MEDIUM * 1.5,
  MESSAGE_CONTENTS_TOP_MARGIN: 5,
  MESSAGE_PARAGRAPH_TOP_MARGIN: MEDIUM,
  MESSAGE_REACTIONS_TOP_MARGIN: SMALL,
  MESSAGE_REACTIONS_BOTTOM_MARGIN: -MEDIUM,
  MESSAGE_SEEN_BY_BOTTOM_MARGIN: MEDIUM,
  MESSAGE_REACTIONS_FACEPILE_OVERLAP: 6,
  MESSAGE_PAST_REACTION_HEIGHT: LARGE,
  MESSAGE_ANNOTATION_HEIGHT_PX: 40,
  MESSAGES_KEBAB_MENU_WIDTH_PX: 196,
  MESSAGE_HEIGHT_TRUNCATE_AT_PX: 300,
  MESSAGE_HEIGHT_TRUNCATE_TO_PX: 200,
  INFINITE_SCROLL_THRESHOLD_PX: 400,
  MESSAGE_ATTACHMENT_PLACEHOLDER_HEIGHT_PX: 92,
  // 277 is the height of kebab menu for your own message, with one line of 'seen by'
  // We set the minHeight of the share to slack menu to this
  MIN_KEBAB_SLACK_MENU_HEIGHT: 277,
  // Distance between kebab menu and kebab menu icon
  KEBAB_MENU_OFFSET: SMALL,

  // Bullets / numbered / todo lists
  BULLET_PADDING_LEFT: CHECKBOX_DEFAULT_SIZE_PX + MEDIUM,

  // Todo - feed this into the menu itself (prob via more dynamic svg)
  MESSAGE_MENU_HEIGHT: 32,

  // Tooltip
  TOOLTIP_HORIZONTAL_PADDING_PX: MEDIUM,
  TOOLTIP_VERTICAL_PADDING_PX: SMALL,
  TOOLTIP_LINE_HEIGHT_PX: LARGE,
  TOOLTIP_MAX_WIDTH_PX: 180,
  ANNOTATION_TOOLTIP_MAX_WIDTH_PX: 180,

  // Attachments
  ATTACHMENT_THUMBNAIL_PX: 58,
  PDF_ATTACHMENT_PX: 90,

  // Modal
  MODAL_SELECT_CHANNELS_MAX_HEIGHT_PX: 240,

  // ImageModal
  IMAGE_MODAL_SMALL_SCALE: 0.66,
  IMAGE_MODAL_BUTTON_HEIGHT_SCALE_PX: 40,
  IMAGE_MODAL_MENU_MAX_WIDTH_PX: 180,
  IMAGE_MODAL_MENU_TOP_POSITION_PX: 44,

  // Success Popup
  SUCCESS_POPUP_HEIGHT: 36,

  // Annotation pointer
  ANNOTATION_POINTER_MIN_GAP_VS_SCREEN_EDGE: MEDIUM,
  ANNOTATION_POINTER_SMALL_SIZE_PX: 34, // 32 + 1 for border on each side, which is included in the svg

  // Annotation arrow
  ANNOTATION_ARROW_CIRCLE_RADIUS: 4,
  ANNOTATION_ARROW_HORIZONTAL_MARGIN_FOR_TOOLTIP: XXLARGE,

  // Charts in webpage
  MIN_CHART_SIZE_PX: 50,
  MAX_CHART_CONTAINER_SIZE_RATIO: 1.25,

  // Login
  LOGIN_BUTTON_WIDTH_PX: 354,
  LOGIN_BUTTON_HEIGHT_PX: 56,
  LOGIN_MARGIN_PX: 56,
  LOGIN_BUTTON_TEXT_SIZE_PX: 18,
  LOGIN_TITLE_TEXT_SIZE_PX: 36,
  EMAIL_PROMPT_HEIGHT_PX: 128,
  EMAIL_PROMPT_INPUT_VERTICAL_PADDING_PX: 14,

  // Welcome
  WELCOME_PARAGRAPH_MAX_WIDTH_PX: 400,
  WELCOME_VIDEO_MAX_HEIGHT_PX: 300,
  WELCOME_VIDEO_MAX_WIDTH_PX: 600,

  // Workspace
  WORKSPACE_HORIZONTAL_MARGIN_PX: 56,
  WORKSPACE_VERTICAL_GAP_PX: 40,
  WORKSPACE_VERTICAL_GAP_SMALL_PX: 32,
  WORKSPACE_SMALL_PADDING_PX: 12,
  WORKSPACE_XSMALL_PADDING_PX: 6,
  WORKSPACE_PARAGRAPH_MAX_WIDTH_PX: 480,
  WORKSPACE_WIDTH_PX: 576,
  WORKSPACE_LOGIN_WIDTH_PX: 640,
  WORKSPACE_LOGIN_BUTTON_HEIGHT_PX: 48,
  WORKSPACE_LOGIN_ORG_IMAGE_SIZE_PX: XXXLARGE,
  WORKSPACE_GET_STARTED_STEP_MAX_WIDTH_PX: 290,
  WORKSPACE_GET_STARTED_STEP_MIN_WIDTH_PX: 230,
  RECENTLY_SHARED_MIN_WIDTH_PX: 120,
  RECENTLY_SHARED_MAX_WIDTH_PX: 240,
  UPDATES_MAX_WIDTH_PX: 320,

  // Extension popup
  EXTENSION_POPUP_WIDTH: 360,
  EXTENSION_POPUP_HEIGHT: 540,
  EXTENSION_POPUP_START_CONVERSATION_BUTTON_HEIGHT: 60,

  SPINNER_DEFAULT_HEIGHT_PX: 20,
  SPINNER_LARGE_HEIGHT_PX: 40,
  CHECKBOX_DEFAULT_SIZE_PX,

  DEFAULT_ICON_SIZE: 24,
  SMALL_ICON_SIZE: 16,
  X_SMALL_ICON_SIZE: 12,

  DEFAULT_BORDER_WIDTH: 1,

  COLLAPSED_THREAD_MESSAGE_HEIGHT: 44,
  ADD_THREAD_BUTTONS_HEIGHT: 60,
  GAP_BETWEEN_THREADS: XLARGE,
  GAP_BETWEEN_GROUPED_THREADS: MEDIUM,
  LOAD_OLDER_MESSAGES_BUTTON_HEIGHT: 33,

  THREAD_MESSAGE_PADDING: MEDIUM,

  SCREENSHOT_BLUR_PX: 10,

  //Screen Size for Embed

  MINIMUM_SCREEN_WIDTH: 600,
  MINIMUM_SCREEN_HEIGHT: 600,

  // Puppet Auth
  PUPPET_MODAL_TOP_MARGIN: 60,
  PUPPET_MODAL_TOP_PADDING: 36,
  PUPPET_MODAL_PADDING: 40,
  PUPPET_MODAL_VERTICAL_PADDING_BUTTON: 10,
  PUPPET_MODAL_VERTICAL_PADDING_TEXT_FIELD: 10,

  // Launcher / Close sidebar button
  LAUNCHER_ICON_HEIGHT: 60,
  LAUNCHER_ICON_WIDTH: 60,
  CLOSE_SIDEBAR_ICON_HEIGHT: 60,
  CLOSE_SIDEBAR_ICON_WIDTH: 60,
  LAUNCHER_FIXED_RIGHT_LENGTH: 16,
  LAUNCHER_FIXED_BOTTOM_LENGTH: 16,

  XSMALL,
  SMALL,
  MEDIUM,
  LARGE,
  XLARGE,
  XXLARGE,
  XXXLARGE,
};

export type FontSize =
  | 'xSmall'
  | 'small'
  | 'default'
  | 'large'
  | 'xLarge'
  | 'inherit';
export const FontSizes: {
  [fontSize in FontSize]: number | string;
} = {
  xSmall: Sizes.X_SMALL_TEXT_SIZE_PX,
  small: Sizes.SMALL_TEXT_SIZE_PX,
  default: Sizes.DEFAULT_TEXT_SIZE_PX,
  large: Sizes.LARGE_TEXT_SIZE_PX,
  xLarge: Sizes.X_LARGE_TEXT_SIZE_PX,
  inherit: 'inherit',
};

export const LineHeights: { [fontSize in FontSize]: string } = {
  xSmall: `${Sizes.SMALL_LINE_HEIGHT_PX}px`,
  small: `${Sizes.SMALL_LINE_HEIGHT_PX}px`,
  default: `${Sizes.DEFAULT_LINE_HEIGHT_PX}px`,
  large: `${Sizes.LARGE_LINE_HEIGHT_PX}px`,
  xLarge: `${Sizes.X_LARGE_LINE_HEIGHT_PX}px`,
  inherit: 'inherit',
};

export const MESSAGE_BLOCK_AVATAR_SIZE = 'l';

export const DEFAULT_EMAIL_LOGO_WIDTH = '140';
