import { Link } from 'react-router-dom';
import EmphasisCard from 'docs/server/ui/card/EmphasisCard.tsx';
import CodeBlock from 'docs/server/ui/codeBlock/CodeBlock.tsx';
import HR from 'docs/server/ui/hr/HR.tsx';

import Page from 'docs/server/ui/page/Page.tsx';
import { H3, H4 } from 'docs/server/ui/typography/Typography.tsx';
import SimplePropertiesList from 'docs/server/ui/propertiesList/SimplePropertiesList.tsx';
import apiData from 'docs/server/apiData/apiData.ts';
import { adjustAutogeneratedProperties } from 'docs/server/ui/propertiesList/util.ts';

function Applications() {
  return (
    <Page
      pretitle="REST API"
      pretitleLinkTo="/rest-apis"
      title="Projects"
      pageSubtitle={`All available operations for manipulating projects and their information`}
      showTableOfContents={true}
    >
      <H3>Create a project</H3>
      <p>
        This endpoint creates a project that can then be viewed and managed
        within the <a href="https://console.cord.com/">Cord Console</a>.
      </p>
      <EmphasisCard>
        <p>
          Note: This feature is only available on paid plans. To use this
          endpoint, create a{' '}
          <Link to="/reference/authentication#Project-management-auth-token">
            project management authentication token
          </Link>{' '}
          using your customer ID and secret. This token is a customer-level
          server auth token used only for the projects REST API.
        </p>
      </EmphasisCard>

      <H4>HTTP Request</H4>
      <CodeBlock
        snippetList={[
          {
            language: 'http',
            languageDisplayName: 'HTTP',
            snippet: `POST https://api.cord.com/v1/projects`,
          },
          {
            language: 'bash',
            languageDisplayName: 'cURL',
            snippet: `curl "https://api.cord.com/v1/projects" \\
-X POST \\
-H 'Authorization: Bearer <ACCESS_TOKEN>' \\
-H 'Content-Type: application/json' \\
            `,
          },
          {
            language: 'bash',
            languageDisplayName: 'CLI',
            snippet: `# you can install @cord-sdk/cli for a simpler experience
cord project create`,
          },
        ]}
      />
      <H4 data-collapsible>Request Body</H4>
      <p>
        Listed below are the fields of the request body to be added as part of
        the HTTP POST request.
      </p>
      <SimplePropertiesList
        level={5}
        properties={adjustAutogeneratedProperties(
          apiData.types.ServerCreateApplication.properties,
          { moveToBack: ['emailSettings'] },
        )}
      />
      <HR />
      <H4>Example Request</H4>
      <CodeBlock
        snippetList={[
          {
            language: 'bash',
            languageDisplayName: 'cURL',
            snippet: `curl "https://api.cord.com/v1/projects" \\
  -X POST \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>' \\
  -H 'Content-Type: application/json' \\
  -d '{
    "name": "Planet Express"
  }'`,
          },
          {
            language: 'bash',
            languageDisplayName: 'CLI',
            snippet: `# you can install @cord-sdk/cli for a simpler experience
cord project create --name="Planet Express"`,
          },
        ]}
      />
      <p>If the request succeeds, the response will be:</p>
      <CodeBlock
        snippetList={[
          {
            language: 'json',
            languageDisplayName: 'JSON',
            snippet: `{
    "success": true,
    "message": "Project created",
    "projectID": "<PROJECT_ID>",
    "secret": "<SECRET_KEY>"
}`,
          },
        ]}
      />
      <p>
        The project <code>secret</code> that you created above is extremely
        sensitive. You should protect it just like you would a password or other
        sensitive credential. This token is used for server-to-server
        communication and should never be used in the browser. For more
        information, check out our{' '}
        <a href="https://docs.cord.com/reference/authentication">
          Authentication reference guide
        </a>{' '}
      </p>
      <p>
        If the request does not succeed, the response will instead contain an{' '}
        <code>error</code> and <code>message</code> explaining what went wrong:
      </p>
      <CodeBlock
        snippetList={[
          {
            language: 'json',
            languageDisplayName: 'JSON',
            snippet: `{
  "error": "<ERROR_CODE>",
  "message": "An explanation of the error code."
}`,
          },
        ]}
      />
      <HR />

      <section>
        <H3>Update a project</H3>
        <p>This endpoint lets you update various properties of your project.</p>
        <H4>HTTP Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'http',
              languageDisplayName: 'HTTP',
              snippet: `PUT https://api.cord.com/v1/projects/<ID>`,
            },
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl "https://api.cord.com/v1/projects/<ID>" \\
  -X PUT \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>' \\
  -H 'Content-Type: application/json' \\`,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord project update <ID>`,
            },
          ]}
        />
        <H4 data-collapsible>Request Body</H4>
        <p>The request body will be a JSON object with two optional fields.</p>
        <SimplePropertiesList
          level={5}
          properties={adjustAutogeneratedProperties(
            apiData.types.ServerUpdateApplication.properties,
            { moveToBack: ['emailSettings'] },
          )}
        />{' '}
        <HR />
        <H4>Example Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl "https://api.cord.com/v1/projects/<ID>" \\
  -X PUT \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>' \\
  -H 'Content-Type: application/json' \\
  -d '{
    "name": "Planet Express, Inc"
  }'`,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord project update <ID> --name="Planet Express, Inc"`,
            },
          ]}
        />
        <p>If the request succeeds, the response will be:</p>
        <CodeBlock
          snippetList={[
            {
              language: 'json',
              languageDisplayName: 'JSON',
              snippet: `{
    "success": true,
    "message": "✅ You successfully updated project <ID>",
}`,
            },
          ]}
        />
        <HR />
      </section>

      <section>
        <H3>List projects</H3>
        <p>This endpoint lists all your projects.</p>
        <H4>HTTP Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'http',
              languageDisplayName: 'HTTP',
              snippet: `GET https://api.cord.com/v1/projects`,
            },
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl "https://api.cord.com/v1/projects" \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>' \\
              `,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord project ls`,
            },
          ]}
        />
        <H4>Request Body</H4>
        <p>
          <em>This REST endpoint has no request body.</em>
        </p>
        <H4 data-collapsible>Response</H4>
        <p>The response is a list of objects with the following fields:</p>
        <SimplePropertiesList
          level={5}
          showRequired={false}
          properties={apiData.types.ApplicationData.properties}
        />
        <H4>Example Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl "https://api.cord.com/v1/projects" \\
  -H "Authorization: Bearer <ACCESS_TOKEN>"`,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord project ls`,
            },
          ]}
        />
        <p>If successful, the response will be similar to:</p>
        <CodeBlock
          snippetList={[
            {
              language: 'json',
              languageDisplayName: 'JSON',
              snippet: `[
  {
    "id": "124",
    "name": "Planet Express",
    "iconURL": null,
  },
  {
    "id": "123",
    "name": "Awesome Express",
    "iconURL": null,
  }
]`,
            },
          ]}
        />
      </section>
      <HR />
      <section>
        <H3>Get a Project</H3>
        <p>This endpoint returns data about a single project.</p>
        <H4>HTTP Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'http',
              languageDisplayName: 'HTTP',
              snippet: `GET https://api.cord.com/v1/projects/<ID>`,
            },
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl "https://api.cord.com/v1/projects<ID>" \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>'`,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord project get <ID>`,
            },
          ]}
        />
        <H4>Request Body</H4>
        <p>
          <em>This REST endpoint has no request body.</em>
        </p>
        <H4 data-collapsible>Response</H4>
        <p>The response is an object with the following fields:</p>
        <SimplePropertiesList
          level={5}
          showRequired={false}
          properties={apiData.types.ApplicationData.properties}
        />
        <H4>Example Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl "https://api.cord.com/v1/projects/124" \\
  -H "Authorization: Bearer <ACCESS_TOKEN>"`,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord project get 124`,
            },
          ]}
        />
        <p>If successful, the response will be similar to:</p>
        <CodeBlock
          snippetList={[
            {
              language: 'json',
              languageDisplayName: 'JSON',
              snippet: `{
  "id": "124",
  "name": "Planet Express",
  "iconURL": null,
}`,
            },
          ]}
        />
      </section>
      <HR />
      <section>
        <H3>Delete a Project</H3>
        <p>
          This endpoint lets you delete your project and any associated data.
          <strong>
            This operation will permanently delete the project along with any
            groups, users, threads and messages associated with that project.
            Please only use if you are okay with that.
          </strong>
        </p>
        <H4>HTTP Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'http',
              languageDisplayName: 'HTTP',
              snippet: `DELETE https://api.cord.com/v1/projects/<ID>`,
            },
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl "https://api.cord.com/v1/projects" \\
  -X DELETE \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>' \\
  -H 'Content-Type: application/json' \\`,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord project delete <ID>`,
            },
          ]}
        />
        <H4>Request Body</H4>
        <p>The request body contains only one field:</p>
        <SimplePropertiesList
          properties={apiData.types.ServerDeleteApplication.properties}
          level={5}
        />
        <HR />
        <H4>Example Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl "https://api.cord.com/v1/projects/<ID>" \\
  -X DELETE \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>' \\
  -H 'Content-Type: application/json' \\
  -d '{
    "secret": <SECRET_KEY>
  }'
    `,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord project delete <ID>

# you will be prompted to input the project secret to confirm deletion              
              `,
            },
          ]}
        />
        <p>If the request succeeds, the response will be:</p>
        <CodeBlock
          snippetList={[
            {
              language: 'json',
              languageDisplayName: 'JSON',
              snippet: `{
    "success": true,
    "message": "💀 You successfully deleted project <ID>",
}`,
            },
          ]}
        />
      </section>
    </Page>
  );
}

export default Applications;
