import { Link } from 'react-router-dom';

import CodeBlock from 'docs/server/ui/codeBlock/CodeBlock.tsx';
import HR from 'docs/server/ui/hr/HR.tsx';
import Page from 'docs/server/ui/page/Page.tsx';
import SimplePropertiesList from 'docs/server/ui/propertiesList/SimplePropertiesList.tsx';
import { H3, H4 } from 'docs/server/ui/typography/Typography.tsx';
import apiData from 'docs/server/apiData/apiData.ts';
import { adjustAutogeneratedProperties } from 'docs/server/ui/propertiesList/util.ts';

export default function Threads() {
  return (
    <Page
      pretitle="Rest API"
      pretitleLinkTo="/rest-apis"
      title="Threads"
      pageSubtitle="All available operations for listing and editing threads"
      showTableOfContents
    >
      <section>
        <H3>List all threads</H3>
        <p>This endpoint returns information about all threads in a project.</p>
        <H4>HTTP Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'http',
              languageDisplayName: 'HTTP',
              snippet: 'GET https://api.cord.com/v1/threads/',
            },
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl https://api.cord.com/v1/threads/ \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>'`,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord thread ls`,
            },
          ]}
        />
        <H4>Request Body</H4>
        <p>
          <em>This REST endpoint has no request body.</em>
        </p>
        <H4 data-collapsible>Request Parameters</H4>
        <p>
          The endpoint supports an optional query request parameter. The filter
          parameter allows you to specify any/all of the multiple optional
          filters which the threads must match. This is a partial match where as
          long as the value you filter by is on the thread it will be returned.
        </p>
        <SimplePropertiesList
          properties={apiData.types.ServerListThreadParameters.properties}
          level={5}
        />
        <H4 data-collapsible>Response</H4>
        <p>
          The response is a JSON Array with objects with the following fields:
        </p>
        <SimplePropertiesList
          showRequired={false}
          properties={apiData.types.ServerListThreads.properties}
          level={5}
        />
      </section>
      <HR />
      <section>
        <H3>Create a thread</H3>
        <p>
          This endpoint is used to create an empty thread. To create a thread
          with a message, please use our{' '}
          <Link to="/rest-apis/messages#createThread">Message API</Link>.
        </p>
        <H4>HTTP Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'http',
              languageDisplayName: 'HTTP',
              snippet: 'POST https://api.cord.com/v1/threads',
            },
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl https://api.cord.com/v1/threads \\
              -X POST \\
              -H 'Authorization: Bearer <ACCESS_TOKEN>'//
              -H 'Content-Type: application/json' `,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord thread create [ID]`,
            },
          ]}
        />
        <H4 data-collapsible>Request Body</H4>
        <SimplePropertiesList
          level={5}
          properties={adjustAutogeneratedProperties(
            apiData.types.ServerCreateThread.properties,
            { moveToBack: ['addSubscribers'] },
          )}
        />
        <H4>Example Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl "https://api.cord.com/v1/threads" \\
  -X POST \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>' \\
  --json '{
  "id": "abc123",
  "name": "my-awesome-thread",
  "groupID": "group123",
  "location": {"category": "sales"}
  }'`,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord thread create abc123 --name=my-awesome-thread --group-id=group123 --location='{"category": "sales"}'`,
            },
          ]}
        />
        <H4>Response</H4>
        <p>If successful, the response will be:</p>
        <CodeBlock
          snippetList={[
            {
              language: 'json',
              languageDisplayName: 'JSON',
              snippet: `{
  "success": true,
  "message": "Thread created.",
  "threadID": "abc123"
}`,
            },
          ]}
        />
      </section>
      <HR />
      <section>
        <H3>Get a thread</H3>
        <p>This endpoint gets information about a specific thread.</p>
        <H4>HTTP Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'http',
              languageDisplayName: 'HTTP',
              snippet: 'GET https://api.cord.com/v1/threads/<ID>',
            },
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl https://api.cord.com/v1/threads/<ID> \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>'`,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord thread get <ID>`,
            },
          ]}
        />
        <H4>Request Body</H4>
        <p>
          <em>This REST endpoint has no request body.</em>
        </p>
        <H4 data-collapsible>Response</H4>
        <p>The response is a JSON object with the following fields:</p>
        <SimplePropertiesList
          showRequired={false}
          properties={apiData.types.CoreThreadData.properties}
          level={5}
        />
      </section>
      <HR />
      <section>
        <H3>Update a thread</H3>
        <p>This endpoint updates an existing thread.</p>
        <H4>HTTP Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'http',
              languageDisplayName: 'HTTP',
              snippet: 'PUT https://api.cord.com/v1/threads/<ID>',
            },
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl https://api.cord.com/v1/threads/<ID> \\
  -X PUT \\            
  -H 'Authorization: Bearer <ACCESS_TOKEN>'\\
  -H 'Content-Type: application/json`,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord thread update <ID>`,
            },
          ]}
        />
        <H4 data-collapsible>Request Body</H4>
        <p>
          Listed below are the fields of the request body to be added as part of
          the HTTP PUT request.
        </p>
        <SimplePropertiesList
          properties={apiData.types.ServerUpdateThread.properties}
          level={5}
        />
        <H4>Response</H4>
        <p>If successful, the response will be:</p>
        <CodeBlock
          snippetList={[
            {
              language: 'json',
              languageDisplayName: 'JSON',
              snippet: `{
  "success": true,
  "message": "✅ You successfully updated thread abc123"
}`,
            },
          ]}
        />
      </section>
      <section>
        <H3>Delete a thread</H3>
        <p>This endpoint deletes a thread.</p>
        <H4>HTTP Request</H4>
        <CodeBlock
          snippetList={[
            {
              language: 'http',
              languageDisplayName: 'HTTP',
              snippet: 'DELETE https://api.cord.com/v1/threads/<ID>',
            },
            {
              language: 'bash',
              languageDisplayName: 'cURL',
              snippet: `curl https://api.cord.com/v1/threads/<ID> \\
  -X DELETE \\
  -H 'Authorization: Bearer <ACCESS_TOKEN>'`,
            },
            {
              language: 'bash',
              languageDisplayName: 'CLI',
              snippet: `# you can install @cord-sdk/cli for a simpler experience
cord thread delete <ID>`,
            },
          ]}
        />
        <H4>Request Body</H4>
        <p>
          <em>This REST endpoint has no request body.</em>
        </p>
        <H4>Response</H4>
        <p>If successful, the response will be:</p>
        <CodeBlock
          snippetList={[
            {
              language: 'json',
              languageDisplayName: 'JSON',
              snippet: `{
  "success": true,
  "message": "💀 You successfully deleted thread abc123"
}`,
            },
          ]}
        />
      </section>
    </Page>
  );
}
