// @ts-nocheck

// This file exists because the @phosphor-icons/react TS types import the icons
// without a file extension, and our tsconfig settings don't support that.  The
// bundled code imports these values just fine, it's only the typechecking that
// fails, so we put all the imports into this file (which is not type-checked)
// and then reexport them.

import {
  Archive,
  ArrowBendDownRight,
  ArrowCircleUpRight,
  ArrowSquareOut,
  ArrowsInSimple,
  ArrowUDownLeft,
  At,
  Bell,
  BellSlash,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  Chats,
  ChatText,
  Check,
  Checks,
  CheckCircle,
  CheckSquare,
  CircleNotch,
  Code,
  Copy,
  DotsThree,
  EnvelopeSimple,
  Export,
  EyeSlash,
  Faders,
  File,
  FileAudio,
  FileCsv,
  FileDoc,
  FilePdf,
  FileText,
  FileVideo,
  FileXls,
  FileZip,
  Gear,
  Hash,
  ImageSquare,
  Info,
  LinkSimple,
  MagnifyingGlass,
  MicrosoftWordLogo,
  MegaphoneSimple,
  Moon,
  Paperclip,
  PencilSimpleLine,
  Question,
  Smiley,
  Square,
  Sun,
  TextAa,
  Trash,
  Tray,
  UserCirclePlus,
  Users,
  WarningCircle,
  X,
} from '@phosphor-icons/react';

// Icon names must be unique across PHOSPHOR_ICONS and CORD_ICONS - e.g. can't
// have an icon called 'Settings' in both
export const UNTYPED_PHOSPHOR_ICONS = {
  Archive,
  ArrowBendDownRight,
  ArrowUDownLeft,
  ArrowCircleUpRight,
  ArrowSquareOut,
  ArrowsInSimple,
  At,
  Bell,
  BellSlash,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  Chats,
  ChatText,
  Check,
  Checks,
  CheckCircle,
  CheckSquare,
  CircleNotch,
  Code,
  Copy,
  DotsThree,
  EnvelopeSimple,
  Export,
  EyeSlash,
  Faders,
  File,
  FileAudio,
  FileCsv,
  FileDoc,
  FilePdf,
  FileText,
  FileVideo,
  FileXls,
  FileZip,
  Gear,
  Hash,
  ImageSquare,
  Info,
  LinkSimple,
  MagnifyingGlass,
  MicrosoftWordLogo,
  MegaphoneSimple,
  Moon,
  Paperclip,
  PencilSimpleLine,
  Question,
  Smiley,
  Square,
  Sun,
  TextAa,
  Trash,
  Tray,
  UserCirclePlus,
  Users,
  WarningCircle,
  X,
};
